[config]

[templates.tmux]
input_path = "~/.config/matugen/templates/tmux-colors.conf"
output_path = "~/.tmux/tmux-colors.conf"
post_hook = "tmux source-file ~/.tmux/tmux-colors.conf"

[templates.mango]
input_path = "~/.config/matugen/templates/mango.conf"
output_path = "~/.config/mango/colors.conf"

[templates.zathura]
input_path = "~/.config/matugen/templates/colors.zathurarc"
output_path = "~/.config/zathura/colors.zathurarc"
