# : Manager [[[

[mgr]
cwd = { fg = "#dee3e7" }

# Tab
tab_active = { fg = "#003547", bg = "#7ed6ff", bold = true }
tab_inactive = { fg = "#bfe8ff", bg = "#001f2b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffaa55", bg = "#ffaa55" }
marker_cut = { fg = "#ffddbb", bg = "#ffddbb" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffbf79", bg = "#ffbf79" }

# Count
count_copied = { fg = "#2b1700", bg = "#ffddbb" }
count_cut = { fg = "#2b1700", bg = "#ffddbb" }
count_selected = { fg = "#003547", bg = "#ffbf79" }

# Border
border_symbol = " "
border_style  = { fg = "#6ed2ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#003547", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#7ed6ff", fg = "#003547", bold = true }
normal_alt  = { bg = "#3d484f", fg = "#bcc8d0" }

# Select mode
select_main = { bg = "#a1cde4", fg = "#003547", bold = true }
select_alt  = { bg = "#3d484f", fg = "#bcc8d0" }

# Unset mode
unset_main = { bg = "#ffbf79", fg = "#482900", bold = true }
unset_alt  = { bg = "#3d484f", fg = "#bcc8d0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#7ed6ff", bg = "#343a3d" }
progress_error = { fg = "#ffb4ab", bg = "#343a3d" }

# Permissions
permissions_t = { fg = "#358ab7" }
permissions_w = { fg = "#df7400" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff9122" }
permissions_s = { fg = "#26b1ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#7ed6ff" }
active = { fg = "#ffbf79", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#7ed6ff" }
value = { fg = "#dee3e7" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#7ed6ff", bold = true, bg = "#0e1417" }
inactive = { fg = "#a1cde4", bg = "#0e1417" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#7ed6ff", bg = "#003547" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7ed6ff" }
title = {}
hovered = { fg = "#ffddbb", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3d" }
cand = { fg = "#7ed6ff" }
rest = { fg = "#003547" }
desc = { fg = "#dee3e7" }
separator = " ▶ "
separator_style = { fg = "#dee3e7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee3e7" }
run = { fg = "#dee3e7" }
footer = { fg = "#003547", bg = "#a1cde4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffbf79" }
title_warn = { fg = "#7ed6ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee3e7" },
    { name = "*/", fg = "#6ed2ff" },
]

# : ]]]
