local telescope = require("telescope")
local actions = require("telescope.actions")

telescope.setup({
   defaults = {
      path_display = { "smart" },
      mappings = {
         i = {
            ["<C-p>"] = actions.move_selection_previous,
            ["<C-n>"] = actions.move_selection_next,
            ["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
         },
      },
   },
})
telescope.load_extension("fzf")

local keymap = vim.keymap
local builtin = require("telescope.builtin")

keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Fuzzy find files in cwd" })
keymap.set("n", "<leader>faf", function()
   builtin.find_files({ hidden = true })
end, { desc = "Fuzzy find files in cwd including hidden" })
keymap.set("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>", { desc = "Fuzzy find recent files" })
keymap.set("n", "<leader>fs", "<cmd>Telescope live_grep<cr>", { desc = "Find string in cwd" })
keymap.set("n", "<leader>fas", function()
   builtin.live_grep({ additional_args = { "--hidden" } })
end, { desc = "Find string in cwd including hidden files" })
keymap.set("n", "<leader>fc", "<cmd>Telescope grep_string<cr>", { desc = "Find string under cursor in cwd" })
keymap.set("n", "<leader>ft", "<cmd>TodoTelescope<cr>", { desc = "Find todos" })

-- Telescope theming.
-- base16-nvim's defaults give telescope invisible borders and a flat grey
-- prompt, so we override the Telescope* groups using the live matugen palette
-- (`base16-colorscheme.colors`). This lives here rather than in dankcolors.lua
-- because that file is regenerated by matugen/dank-material-shell. base16's
-- setup() runs `syntax reset`, which wipes these on every reload, so we re-apply
-- via an fs-watcher on dankcolors.lua (registered after dankcolors' own watcher,
-- so base16 has re-applied by the time we run).
local function apply_telescope_theme()
   local ok, base16 = pcall(require, "base16-colorscheme")
   local c = ok and base16.colors
   if not c then
      return
   end
   local set = vim.api.nvim_set_hl
   -- window backgrounds (solid base00)
   set(0, "TelescopeNormal", { fg = c.base05, bg = c.base00 })
   set(0, "TelescopePromptNormal", { fg = c.base05, bg = c.base00 })
   set(0, "TelescopeResultsNormal", { fg = c.base05, bg = c.base00 })
   set(0, "TelescopePreviewNormal", { fg = c.base05, bg = c.base00 })
   -- visible accent borders
   set(0, "TelescopeBorder", { fg = c.base0D, bg = c.base00 })
   set(0, "TelescopePromptBorder", { fg = c.base0D, bg = c.base00 })
   set(0, "TelescopeResultsBorder", { fg = c.base0D, bg = c.base00 })
   set(0, "TelescopePreviewBorder", { fg = c.base0D, bg = c.base00 })
   -- accent title chips
   set(0, "TelescopePromptTitle", { fg = c.base00, bg = c.base0D, bold = true })
   set(0, "TelescopeResultsTitle", { fg = c.base00, bg = c.base0D, bold = true })
   set(0, "TelescopePreviewTitle", { fg = c.base00, bg = c.base0D, bold = true })
   -- prompt + selection
   set(0, "TelescopePromptPrefix", { fg = c.base0D, bg = c.base00 })
   set(0, "TelescopePromptCounter", { fg = c.base03, bg = c.base00 })
   set(0, "TelescopeSelection", { fg = c.base00, bg = c.base02, bold = true })
   set(0, "TelescopeSelectionCaret", { fg = c.base0D, bg = c.base02 })
   set(0, "TelescopeMatching", { fg = c.base0B, bold = true })
end

apply_telescope_theme()

if not _G._telescope_theme_watcher then
   local uv = vim.uv or vim.loop
   local dankcolors_path = vim.fn.stdpath("config") .. "/lua/plugins/dankcolors.lua"
   _G._telescope_theme_watcher = uv.new_fs_event()
   _G._telescope_theme_watcher:start(dankcolors_path, {}, vim.schedule_wrap(apply_telescope_theme))
end
